### ISSUE TITLE
yarn global add vtex - It does not allow installing or updating the vtex toolbet through the terminal.

### ISSUE THREAD

**Issue by brendonguedes** [vtex/toolbelt#802]
* yarn global add vtex - It does not allow installing or updating the vtex toolbet through the terminal 

## Expected Behavior
When running "yarn global add vtex" I expected the toolbelt to be updated, just like when I run "npm -g install vtex"

## My Environment
* This morning when executing "vtex link" the terminal returned an update request from CLi vtex, suggesting that I run "yarn global add vtex" to be updated to the latest stable version. The installed version was 2.92.3 and the most current stable version was 2.94.0.
I ran the command but it didn't update as expected. However, when running "npm -g install vtex" I achieved what was expected and version vtex 2.94.0 was successfully installed. 
* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4): React version 16.13.0 // Node version 12.0.8
* Operating System and version (desktop or mobile): Linux Ubuntu 18.4

**Comment by tiagonapoli** [comment]
We primarily use `yarn` in our development. IO just ignores `package-lock.json` for example, generated by installing dependencies with npm. For this reason we use yarn so it would be better if you could configure `yarn` instead of npm. 

You should delete `vtex` package from the npm installation, I think `npm remove -g vtex` will do the trick.
Then you can install vtex using yarn, `yarn global add vtex`. If you installed yarn correctly evething should work, otherwise you may have to setup your terminal PATH for including the yarn global binaries folder - everything is covered here - https://classic.yarnpkg.com/en/docs/install
(the path topic is in Path Setup)
