### ISSUE TITLE
Allow use of other package managers

### ISSUE THREAD

**Issue by eduardoturconi** [vtex/toolbelt#809]
## Expected Behavior

Allow usage of other package managers, like pnpm or npm.

## Current Behavior

Vtex toolbelt only see's yarn's lockfile.

## Possible Solution

Allow to consider other packages' lockfile, like package-lock.json (npm) and pnpm-lock.yaml (pnpm).

## Context

I want to use another package manager.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node v13.12, pnpm v4.12.4
* Operating System and version (desktop or mobile): Windows 10 2004
* Link to your project: -

**Comment by tiagonapoli** [comment]
Unfortunately this is not a toolbelt's decision to make. You can use toolbelt on other package managers, but we will always recommend to use `yarn`, because if you use `react` or `node` builders you'll have to use `yarn.lock` (builder-hub uses only this).

For now yarn offers almost the same features from npm (from what I know) and the migration is easy. Why would you want to use other package managers? (for the builder-hub developers I think it would add unnecessary complexity to the builder-hub code to support other lockfiles - so maybe it would need good arguments on why you would need to use other package managers)
https://classic.yarnpkg.com/en/docs/install

**Comment by eduardoturconi** [comment]
I want to use `pnpm` and the reasons why the team can view on it's GitHub page: https://github.com/pnpm/pnpm
