### ISSUE TITLE
Intermnitent bug with yellow error page

### ISSUE THREAD

**Issue by dfosco** [vtex/toolbelt#96]
The yellow error page that says “route not found” — usually it comes back after 2-3 refreshes, but it's been constantly happening a few times a day ever since last week.

**Comment by brenoc** [comment]
Open this issue in vtex/storefront please

**Comment by dfosco** [comment]
@brenoc I talked to @brunoabreu and he said this issue comes from the toolbelt — he'll come in and re-open the issue later.

**Comment by brunoabreu** [comment]
@brenoc it happens when the sandboxed app that defines the route is not active, even with toolbelt watching it.

Every 30 seconds toolbelt must send a keep-alive request and if server doesn't receive that, it deactivates the sandboxed app. My guess is that it starts to work properly not because of the refreshes, but because after 30 seconds a new keep-alive request is sent successfully.

We can give this issue a better title and description, but I think it should remain open for investigation.

**Comment by brenoc** [comment]
@dfosco sorry about that :)

Thanks, @brunoabreu!

@tamorim can you think of a thing that may cause this?

**Comment by tamorim** [comment]
@brenoc @brunoabreu @dfosco
Actually this one is solved!
I think the problem was a concurrency issue on the gallery side + the keep alive time!
This is fixed on beta branch, which kinda is the default branch right now!
We keep the master behind for now because it points to the stable version (that tomorrow will change).
